<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d4yii2\costcard\models\base;

use Yii;

/**
 * This is the base-model class for table "cc_cost_card".
 *
 * @property integer $id
 * @property integer $sys_company_id
 * @property integer $previos_cost_card_id
 * @property integer $record_sys_model_id
 * @property integer $record_id
 * @property integer $dimension_id
 * @property string $qnt
 * @property integer $unit_id
 * @property string $unit_price
 * @property string $total_amount
 * @property integer $dimension_model_id
 * @property integer $dimension_record_id
 *
 * @property \d4yii2\costcard\models\CcDimension $dimension
 * @property \d4yii2\costcard\models\SysModels $dimensionModel
 * @property \d4yii2\costcard\models\SysModels $recordSysModel
 * @property \d4yii2\costcard\models\CcUnit $unit
 * @property string $aliasModel
 */
abstract class CcCostCard extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'cc_cost_card';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            'required' => [['sys_company_id', 'record_sys_model_id', 'record_id', 'dimension_id', 'qnt', 'unit_id', 'unit_price', 'total_amount', 'dimension_model_id', 'dimension_record_id'], 'required'],
            'tinyint Unsigned' => [['record_sys_model_id','dimension_id','unit_id','dimension_model_id'],'integer' ,'min' => 0 ,'max' => 255],
            'smallint Unsigned' => [['sys_company_id'],'integer' ,'min' => 0 ,'max' => 65535],
            'integer Unsigned' => [['id','previos_cost_card_id','record_id','dimension_record_id'],'integer' ,'min' => 0 ,'max' => 4294967295],
            [['qnt', 'unit_price', 'total_amount'], 'number'],
            [['dimension_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d4yii2\costcard\models\CcDimension::className(), 'targetAttribute' => ['dimension_id' => 'id']],
            [['dimension_model_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d4yii2\costcard\models\SysModels::className(), 'targetAttribute' => ['dimension_model_id' => 'id']],
            [['record_sys_model_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d4yii2\costcard\models\SysModels::className(), 'targetAttribute' => ['record_sys_model_id' => 'id']],
            [['unit_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d4yii2\costcard\models\CcUnit::className(), 'targetAttribute' => ['unit_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('costcard', 'ID'),
            'sys_company_id' => Yii::t('costcard', 'Sys Company ID'),
            'previos_cost_card_id' => Yii::t('costcard', 'Previos Cost Card'),
            'record_sys_model_id' => Yii::t('costcard', 'Record Model'),
            'record_id' => Yii::t('costcard', 'Record'),
            'dimension_id' => Yii::t('costcard', 'Dimension'),
            'qnt' => Yii::t('costcard', 'Quantity'),
            'unit_id' => Yii::t('costcard', 'Unit'),
            'unit_price' => Yii::t('costcard', 'Unit Price'),
            'total_amount' => Yii::t('costcard', 'Total amount'),
            'dimension_model_id' => Yii::t('costcard', 'Dimension model'),
            'dimension_record_id' => Yii::t('costcard', 'Dimension record'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints(): array
    {
        return array_merge(parent::attributeHints(), [
            'previos_cost_card_id' => Yii::t('costcard', 'Previos Cost Card'),
            'record_sys_model_id' => Yii::t('costcard', 'Record Model'),
            'record_id' => Yii::t('costcard', 'Record'),
            'dimension_id' => Yii::t('costcard', 'Dimension'),
            'qnt' => Yii::t('costcard', 'Quantity'),
            'unit_id' => Yii::t('costcard', 'Unit'),
            'unit_price' => Yii::t('costcard', 'Unit Price'),
            'total_amount' => Yii::t('costcard', 'Total amount'),
            'dimension_model_id' => Yii::t('costcard', 'Dimension model'),
            'dimension_record_id' => Yii::t('costcard', 'Dimension record'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDimension()
    {
        return $this->hasOne(\d4yii2\costcard\models\CcDimension::className(), ['id' => 'dimension_id'])->inverseOf('ccCostCards');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDimensionModel()
    {
        return $this->hasOne(\d4yii2\costcard\models\SysModels::className(), ['id' => 'dimension_model_id'])->inverseOf('ccCostCards');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRecordSysModel()
    {
        return $this->hasOne(\d4yii2\costcard\models\SysModels::className(), ['id' => 'record_sys_model_id'])->inverseOf('ccCostCards0');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUnit()
    {
        return $this->hasOne(\d4yii2\costcard\models\CcUnit::className(), ['id' => 'unit_id'])->inverseOf('ccCostCards');
    }


    
    /**
     * @inheritdoc
     * @return \d4modules\manufacture\models\CcCostCardQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \d4modules\manufacture\models\CcCostCardQuery(get_called_class());
    }

}
