<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d4yii2\costcard\models\base;

use Yii;

/**
 * This is the base-model class for table "cc_label".
 *
 * @property integer $id
 * @property string $name
 * @property integer $sys_model_id
 * @property integer $model_record_id
 * @property integer $add_sys_model_id
 * @property integer $add_model_record_id
 *
 * @property \d4yii2\costcard\models\SysModels $addSysModel
 * @property \d4yii2\costcard\models\CcCostCard[] $ccCostCards
 * @property \d4yii2\costcard\models\SysModels $sysModel
 * @property string $aliasModel
 */
abstract class CcLabel extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'cc_label';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            'required' => [['name', 'sys_model_id'], 'required'],
            'tinyint Unsigned' => [['sys_model_id','add_sys_model_id'],'integer' ,'min' => 0 ,'max' => 255],
            'smallint Unsigned' => [['id'],'integer' ,'min' => 0 ,'max' => 65535],
            'integer Unsigned' => [['model_record_id','add_model_record_id'],'integer' ,'min' => 0 ,'max' => 4294967295],
            [['name'], 'string', 'max' => 50],
            [['sys_model_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d4yii2\costcard\models\SysModels::className(), 'targetAttribute' => ['sys_model_id' => 'id']],
            [['add_sys_model_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d4yii2\costcard\models\SysModels::className(), 'targetAttribute' => ['add_sys_model_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('costcard', 'ID'),
            'name' => Yii::t('costcard', 'Label Name'),
            'sys_model_id' => Yii::t('costcard', 'Sys Model'),
            'model_record_id' => Yii::t('costcard', 'Record'),
            'add_sys_model_id' => Yii::t('costcard', 'Add model'),
            'add_model_record_id' => Yii::t('costcard', 'Add Record'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints(): array
    {
        return array_merge(parent::attributeHints(), [
            'name' => Yii::t('costcard', 'Label Name'),
            'sys_model_id' => Yii::t('costcard', 'Sys Model'),
            'model_record_id' => Yii::t('costcard', 'Record'),
            'add_sys_model_id' => Yii::t('costcard', 'Add model'),
            'add_model_record_id' => Yii::t('costcard', 'Add Record'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAddSysModel()
    {
        return $this->hasOne(\d4yii2\costcard\models\SysModels::className(), ['id' => 'add_sys_model_id'])->inverseOf('ccLabels0');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCcCostCards()
    {
        return $this->hasMany(\d4yii2\costcard\models\CcCostCard::className(), ['label_id' => 'id'])->inverseOf('label');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSysModel()
    {
        return $this->hasOne(\d4yii2\costcard\models\SysModels::className(), ['id' => 'sys_model_id'])->inverseOf('ccLabels');
    }



}
