<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d4yii2\costcard\models\base;

use Yii;

/**
 * This is the base-model class for table "cc_models".
 *
 * @property integer $id
 * @property integer $sys_model_id
 * @property string $class_name
 *
 * @property \d4yii2\costcard\models\SysModels $sysModel
 * @property string $aliasModel
 */
abstract class CcModels extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'cc_models';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            'required' => [['sys_model_id', 'class_name'], 'required'],
            'tinyint Unsigned' => [['id','sys_model_id'],'integer' ,'min' => 0 ,'max' => 255],
            [['class_name'], 'string', 'max' => 256],
            [['sys_model_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d4yii2\costcard\models\SysModels::className(), 'targetAttribute' => ['sys_model_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('costcard', 'ID'),
            'sys_model_id' => Yii::t('costcard', 'Sys Model ID'),
            'class_name' => Yii::t('costcard', 'Class Name'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSysModel()
    {
        return $this->hasOne(\d4yii2\costcard\models\SysModels::className(), ['id' => 'sys_model_id'])->inverseOf('ccModels');
    }


    
    /**
     * @inheritdoc
     * @return \d4modules\manufacture\models\CcModelsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \d4modules\manufacture\models\CcModelsQuery(get_called_class());
    }

}
